name: Bundle

on:
  push: # All branches, but appropriate paths only.
    # branches:
    #   - squeak-trunk
      # - squeak-5.3
      # - squeak-5.2
    paths-ignore:
      - '**.md' # Skip changes in documentation artifacts
  pull_request:
    branches:
      - squeak-trunk
      # - squeak-5.3
      # - squeak-5.2
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 0 * * *' # Build everyday at midnight
  workflow_dispatch:

jobs:
  prepare-image:
    strategy:
      fail-fast: true
      matrix:
        smalltalk:
          - Squeak-trunk
          - Squeak64-trunk
          # - Squeak-5.3
          # - Squeak64-5.3
          # - Squeak-5.2
          # - Squeak64-5.2
    runs-on: windows-latest
    name: 🛠 Prepare image for ${{ matrix.smalltalk }}
    env:
      SMALLTALK_VERSION: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2

      - name: Prepare image
        shell: bash
        run: ./prepare_image.sh
        timeout-minutes: 20

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.smalltalk }}
          path: |
            tmp/*.sources
            tmp/*.image
            tmp/*.changes
            tmp/version.sh
            !tmp/Test*


  test-image:
    needs: [prepare-image]
    strategy:
      fail-fast: true
      matrix:
        smalltalk:
          - Squeak-trunk
          - Squeak64-trunk
          # - Squeak-5.3
          # - Squeak64-5.3
          # - Squeak-5.2
          # - Squeak64-5.2
    runs-on: windows-latest
    name: 🧪 Test image of ${{ matrix.smalltalk }}
    env:
      SMALLTALK_VERSION: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.smalltalk }}
          path: tmp

      - name: "Set up SmalltalkCI"
        # uses: hpi-swa/setup-smalltalkCI@v1
        uses: marceltaeumel/setup-smalltalkCI@marceltaeumel/install-path
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
          smalltalkCI-workspace: ${{ github.workspace }}

      - name: "Run tests"
        continue-on-error: true
        shell: bash
        run: ./test_image.sh
        timeout-minutes: 20

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.smalltalk }}-tests
          path: tmp/*.xml


  prepare-bundles:
    needs: [prepare-image]
    strategy:
      fail-fast: true
      matrix:
        smalltalk:
          - Squeak-trunk
          - Squeak64-trunk
          # - Squeak-5.3
          # - Squeak64-5.3
          # - Squeak-5.2
          # - Squeak64-5.2
    runs-on: macos-latest
    name: 📦 Prepare bundles for ${{ matrix.smalltalk }}
    env:
      SMALLTALK_VERSION: ${{ matrix.smalltalk }}
      GIT_BRANCH: ${{ github.ref }}
      DEPLOYMENT_BRANCH: squeak-trunk

      ENCRYPTED_KEY: ${{ secrets.ENCRYPTED_KEY }}
      ENCRYPTED_IV: ${{ secrets.ENCRYPTED_IV }}
      PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}

      PROXY_PORT: ${{ secrets.PROXY_PORT }}
      PROXY_HOST: ${{ secrets.PROXY_HOST }}
      PROXY_USER: ${{ secrets.PROXY_USER }}
      UPSTREAM_HOST: ${{ secrets.UPSTREAM_HOST }}
      UPSTREAM_USER: ${{ secrets.UPSTREAM_USER }}

      CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
      SIGN_IDENTITY: ${{ secrets.SIGN_IDENTITY }}
      NOTARIZATION_USER: ${{ secrets.NOTARIZATION_USER }}
      NOTARIZATION_PASSWORD: ${{ secrets.NOTARIZATION_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.smalltalk }}
          path: tmp

      - run: ./prepare_bundles.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.smalltalk }}-bundles
          path: product/*

      - run: ./deploy_bundles.sh
        if: endsWith(github.ref, env.DEPLOYMENT_BRANCH)
